/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funwithsearchingandsorting.gui.swing;

import funwithsearchingandsorting.bll.arrayGen.ArrayFactory;
import funwithsearchingandsorting.bll.sorting.ArraySorting;
import funwithsearchingandsorting.bll.timer.MyTimer;
import funwithsearchingandsorting.bll.searching.SearchLogic;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author stegg_000
 */
public class SearchPanel extends javax.swing.JPanel
{

    private MyTimer timer;

    private SearchLogic searchLogic;

    private ArraySorting arraySorter;

    private int[] searchBase;

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel()
    {
        timer = new MyTimer();
        searchLogic = new SearchLogic();
        arraySorter = new ArraySorting();
        initComponents();
        btnGroupSortSelection.add(btnRadioReversed);
        btnGroupSortSelection.add(btnRadioSorted);
        btnGroupSortSelection.add(btnRadioUnsorted);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel3 = new javax.swing.JLabel();
        btnGroupSortSelection = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtListSize = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMinVal = new javax.swing.JTextField();
        txtMaxVal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboSortAlgo = new javax.swing.JComboBox();
        btnCreateArray = new javax.swing.JButton();
        btnRadioUnsorted = new javax.swing.JRadioButton();
        btnRadioSorted = new javax.swing.JRadioButton();
        btnRadioReversed = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        txtSortTime = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFirstIndex = new javax.swing.JTextField();
        txtMiddleIndex = new javax.swing.JTextField();
        txtLastIndex = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        comboSearchType = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtSearchValue = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtSearchResult = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSearchTime = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnTestSorting = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Initiliazing:"));

        jLabel1.setText("List size:");

        jLabel2.setText("Min. value");

        jLabel4.setText("Max. value");

        comboSortAlgo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Java's built in sorting algorithm", "BubbleSort", "SelectionSort", "InsertionSort", "HeapSort", "QuickSort", "MergeSort" }));
        comboSortAlgo.setEnabled(false);
        comboSortAlgo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboSortAlgoActionPerformed(evt);
            }
        });

        btnCreateArray.setText("Create");
        btnCreateArray.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCreateArrayActionPerformed(evt);
            }
        });

        btnRadioUnsorted.setSelected(true);
        btnRadioUnsorted.setText("Unsorted");
        btnRadioUnsorted.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRadioUnsortedActionPerformed(evt);
            }
        });

        btnRadioSorted.setText("Sorted");
        btnRadioSorted.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRadioSortedActionPerformed(evt);
            }
        });

        btnRadioReversed.setText("Reverse sorted");
        btnRadioReversed.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRadioReversedActionPerformed(evt);
            }
        });

        jLabel13.setText("Sorting time:");

        txtSortTime.setEditable(false);

        jLabel14.setText("sec.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtListSize, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMinVal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaxVal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboSortAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateArray, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRadioUnsorted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRadioSorted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRadioReversed))
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSortTime, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtListSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaxVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioUnsorted)
                    .addComponent(btnRadioSorted)
                    .addComponent(btnRadioReversed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSortAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateArray))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSortTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected values:"));

        jLabel5.setText("First value:");

        jLabel6.setText("Middle value:");

        jLabel7.setText("Last value:");

        txtFirstIndex.setEditable(false);

        txtMiddleIndex.setEditable(false);

        txtLastIndex.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtFirstIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtMiddleIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtLastIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMiddleIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Searching:"));

        jLabel8.setText("Algorithm:");

        comboSearchType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Linear Search - Find first", "Linear Search - Find last", "Binary Search", "Binary Search - Find first", "Binary Search - Find last" }));
        comboSearchType.setEnabled(false);

        jLabel9.setText("Search value:");

        txtSearchValue.setEnabled(false);

        btnSearch.setText("Search");
        btnSearch.setEnabled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboSearchType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearchValue))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Search results:"));

        jLabel10.setText("Value found at index:");

        txtSearchResult.setEditable(false);

        jLabel11.setText("sec.");

        txtSearchTime.setEditable(false);

        jLabel12.setText("Search time:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearchResult))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSearchTime, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(jLabel12))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtSearchTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorting"));

        btnTestSorting.setText("Compare Sorting Algorithm's");
        btnTestSorting.setEnabled(false);
        btnTestSorting.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnTestSortingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnTestSorting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTestSorting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateArrayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCreateArrayActionPerformed
    {//GEN-HEADEREND:event_btnCreateArrayActionPerformed
        int size = Integer.parseInt(txtListSize.getText());
        int minVal = Integer.parseInt(txtMinVal.getText());
        int maxVal = Integer.parseInt(txtMaxVal.getText());

        if (btnRadioUnsorted.isSelected())
        {
            searchBase = ArrayFactory.fillArray(size, minVal, maxVal);
            txtSortTime.setText("NaN");
        }
        else if (btnRadioReversed.isSelected())
        {
            timer.reset();
            timer.start();
            searchBase = ArrayFactory.fillSortedArray(size, minVal, maxVal);
            arraySorter.reverse(searchBase);
            timer.stop();
            txtSortTime.setText(timer.getSeconds() + "");
        }
        else
        {
            searchBase = ArrayFactory.fillArray(size, minVal, maxVal);
            doMySortingAlgorithms();
        }

        int firstIndex = searchBase[0];
        int middleIndex = searchBase[searchBase.length / 2];
        int lastIndex = searchBase[searchBase.length - 1];
        txtFirstIndex.setText(firstIndex + "");
        txtMiddleIndex.setText(middleIndex + "");
        txtLastIndex.setText(lastIndex + "");

        btnTestSorting.setEnabled(true);
        comboSearchType.setEnabled(true);
        txtSearchValue.setEnabled(true);
        btnSearch.setEnabled(true);
    }//GEN-LAST:event_btnCreateArrayActionPerformed

    private void doMySortingAlgorithms()
    {
        timer.reset();
        timer.start();
        switch (comboSortAlgo.getSelectedIndex())
        {
            case 0:
                arraySorter.javaSort(searchBase);
                break;
            case 1:
                arraySorter.bubbleSort(searchBase);
                break;
            case 2:
                arraySorter.selectionSort(searchBase);
                break;
            case 3:
                arraySorter.insertionSort(searchBase);
                break;
            case 4:
                arraySorter.heapSort(searchBase);
                break;
            case 5:
                arraySorter.quicksort(searchBase);
                break;
            case 6:
                arraySorter.mergeSort(searchBase);
                break;
        }
        timer.stop();
        txtSortTime.setText(timer.getSeconds() + "");
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
    {//GEN-HEADEREND:event_btnSearchActionPerformed
        int selection = comboSearchType.getSelectedIndex();
        int searchVal = Integer.parseInt(txtSearchValue.getText());
        int index = -1;
        timer.reset();
        timer.start();
        switch (selection)
        {
            case 0:
                index = searchLogic.findFirst(searchVal, searchBase);
                break;
            case 1:
                index = searchLogic.findLast(searchVal, searchBase);
                break;
            case 2:
                index = searchLogic.binSearch(searchVal, searchBase);
                break;
            case 3:
                index = searchLogic.binFindFirst(searchVal, searchBase);
                break;
            case 4:
                index = searchLogic.binFindLast(searchVal, searchBase);
                break;
            default:
                break;
        }
        timer.stop();
        txtSearchResult.setText(index + "");
        txtSearchTime.setText(timer.getSeconds() + "");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void comboSortAlgoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboSortAlgoActionPerformed
    {//GEN-HEADEREND:event_comboSortAlgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSortAlgoActionPerformed

    private void btnRadioSortedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRadioSortedActionPerformed
    {//GEN-HEADEREND:event_btnRadioSortedActionPerformed
        comboSortAlgo.setEnabled(true);
    }//GEN-LAST:event_btnRadioSortedActionPerformed

    private void btnRadioReversedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRadioReversedActionPerformed
    {//GEN-HEADEREND:event_btnRadioReversedActionPerformed
        comboSortAlgo.setEnabled(false);
    }//GEN-LAST:event_btnRadioReversedActionPerformed

    private void btnTestSortingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTestSortingActionPerformed
    {//GEN-HEADEREND:event_btnTestSortingActionPerformed
        SwingUtilities.invokeLater(new Runnable()
        {

            @Override
            public void run()
            {
                JFrame frame = new JFrame("Testing Sorting Algorithms");
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                boolean reversed = btnRadioReversed.isSelected();
                boolean sorted = btnRadioSorted.isSelected() || btnRadioReversed.isSelected();
                SortTestPanel testPanel = new SortTestPanel(searchBase, sorted, reversed);
                frame.add(testPanel);
                frame.pack();
                frame.setResizable(false);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnTestSortingActionPerformed

    private void btnRadioUnsortedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRadioUnsortedActionPerformed
    {//GEN-HEADEREND:event_btnRadioUnsortedActionPerformed
        comboSortAlgo.setEnabled(false);
    }//GEN-LAST:event_btnRadioUnsortedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateArray;
    private javax.swing.ButtonGroup btnGroupSortSelection;
    private javax.swing.JRadioButton btnRadioReversed;
    private javax.swing.JRadioButton btnRadioSorted;
    private javax.swing.JRadioButton btnRadioUnsorted;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTestSorting;
    private javax.swing.JComboBox comboSearchType;
    private javax.swing.JComboBox comboSortAlgo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtFirstIndex;
    private javax.swing.JTextField txtLastIndex;
    private javax.swing.JTextField txtListSize;
    private javax.swing.JTextField txtMaxVal;
    private javax.swing.JTextField txtMiddleIndex;
    private javax.swing.JTextField txtMinVal;
    private javax.swing.JTextField txtSearchResult;
    private javax.swing.JTextField txtSearchTime;
    private javax.swing.JTextField txtSearchValue;
    private javax.swing.JTextField txtSortTime;
    // End of variables declaration//GEN-END:variables
}
